/* 
 * HQ API Entities
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HQ.API.SDK.Api;
using HQ.API.SDK.Model;
using HQ.API.SDK.Client;
using System.Reflection;

namespace HQ.API.SDK.Test
{
    /// <summary>
    ///  Class for testing ArticleSupplierQuotation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ArticleSupplierQuotationTests
    {
        // TODO uncomment below to declare an instance variable for ArticleSupplierQuotation
        //private ArticleSupplierQuotation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ArticleSupplierQuotation
            //instance = new ArticleSupplierQuotation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ArticleSupplierQuotation
        /// </summary>
        [Test]
        public void ArticleSupplierQuotationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ArticleSupplierQuotation
            //Assert.IsInstanceOfType<ArticleSupplierQuotation> (instance, "variable 'instance' is a ArticleSupplierQuotation");
        }

        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Test]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'DeliveryTimeInDays'
        /// </summary>
        [Test]
        public void DeliveryTimeInDaysTest()
        {
            // TODO unit test for the property 'DeliveryTimeInDays'
        }
        /// <summary>
        /// Test the property 'TotalPrice'
        /// </summary>
        [Test]
        public void TotalPriceTest()
        {
            // TODO unit test for the property 'TotalPrice'
        }
        /// <summary>
        /// Test the property 'MinQuantity'
        /// </summary>
        [Test]
        public void MinQuantityTest()
        {
            // TODO unit test for the property 'MinQuantity'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Test]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'ExchangeRate'
        /// </summary>
        [Test]
        public void ExchangeRateTest()
        {
            // TODO unit test for the property 'ExchangeRate'
        }
        /// <summary>
        /// Test the property 'ArticleId'
        /// </summary>
        [Test]
        public void ArticleIdTest()
        {
            // TODO unit test for the property 'ArticleId'
        }
        /// <summary>
        /// Test the property 'SupplierId'
        /// </summary>
        [Test]
        public void SupplierIdTest()
        {
            // TODO unit test for the property 'SupplierId'
        }
        /// <summary>
        /// Test the property 'Supplier'
        /// </summary>
        [Test]
        public void SupplierTest()
        {
            // TODO unit test for the property 'Supplier'
        }
        /// <summary>
        /// Test the property 'Unit'
        /// </summary>
        [Test]
        public void UnitTest()
        {
            // TODO unit test for the property 'Unit'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Test]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Test]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Test]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }

    }

}
