/* 
 * HQ API Entities
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace HQSB.API.SDK.Model
{
    /// <summary>
    /// A company represents any entity you do business with, for example a customer, a supplier or a partner.
    /// </summary>
    [DataContract]
    public partial class Company :  IEquatable<Company>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Company" /> class.
        /// </summary>
        /// <param name="Name">The name of the company.</param>
        /// <param name="IndustrialSector">The company&#39;s industrial sector.</param>
        /// <param name="Description">A longer description of the company.</param>
        /// <param name="DebitorNumber">The company&#39;s debitor number.</param>
        /// <param name="CreditorNumber">The company&#39;s creditor number.</param>
        /// <param name="DefaultAddress">The default address of this company.</param>
        /// <param name="CustomFields">The customfields associated with this company.</param>
        /// <param name="CompanyTypes">The company types associated with this company.</param>
        /// <param name="Id">The unique identifier of this entity.</param>
        /// <param name="CreatedBy">The id of the user who created this entity.</param>
        /// <param name="UpdatedBy">The id of the last user who modified this entity.</param>
        /// <param name="CreatedOn">The date and time this entity was created, in UTC.</param>
        /// <param name="UpdatedOn">The last date and time this entity was updated, in UTC.</param>
        public Company(string Name = null, string IndustrialSector = null, string Description = null, int? DebitorNumber = null, int? CreditorNumber = null, CompanyAddress DefaultAddress = null, List<CustomField> CustomFields = null, List<CompanyType> CompanyTypes = null, int? Id = null, int? CreatedBy = null, int? UpdatedBy = null, DateTime? CreatedOn = null, DateTime? UpdatedOn = null)
        {
            this.Name = Name;
            this.IndustrialSector = IndustrialSector;
            this.Description = Description;
            this.DebitorNumber = DebitorNumber;
            this.CreditorNumber = CreditorNumber;
            this.DefaultAddress = DefaultAddress;
            this.CustomFields = CustomFields;
            this.CompanyTypes = CompanyTypes;
            this.Id = Id;
            this.CreatedBy = CreatedBy;
            this.UpdatedBy = UpdatedBy;
            this.CreatedOn = CreatedOn;
            this.UpdatedOn = UpdatedOn;
        }
        
        /// <summary>
        /// The name of the company
        /// </summary>
        /// <value>The name of the company</value>
        [DataMember(Name="Name", EmitDefaultValue=false)]
        public string Name { get; set; }
        /// <summary>
        /// The company&#39;s industrial sector
        /// </summary>
        /// <value>The company&#39;s industrial sector</value>
        [DataMember(Name="IndustrialSector", EmitDefaultValue=false)]
        public string IndustrialSector { get; set; }
        /// <summary>
        /// A longer description of the company
        /// </summary>
        /// <value>A longer description of the company</value>
        [DataMember(Name="Description", EmitDefaultValue=false)]
        public string Description { get; set; }
        /// <summary>
        /// The company&#39;s debitor number
        /// </summary>
        /// <value>The company&#39;s debitor number</value>
        [DataMember(Name="DebitorNumber", EmitDefaultValue=false)]
        public int? DebitorNumber { get; set; }
        /// <summary>
        /// The company&#39;s creditor number
        /// </summary>
        /// <value>The company&#39;s creditor number</value>
        [DataMember(Name="CreditorNumber", EmitDefaultValue=false)]
        public int? CreditorNumber { get; set; }
        /// <summary>
        /// The default address of this company
        /// </summary>
        /// <value>The default address of this company</value>
        [DataMember(Name="DefaultAddress", EmitDefaultValue=false)]
        public CompanyAddress DefaultAddress { get; set; }
        /// <summary>
        /// The customfields associated with this company
        /// </summary>
        /// <value>The customfields associated with this company</value>
        [DataMember(Name="CustomFields", EmitDefaultValue=false)]
        public List<CustomField> CustomFields { get; set; }
        /// <summary>
        /// The company types associated with this company
        /// </summary>
        /// <value>The company types associated with this company</value>
        [DataMember(Name="CompanyTypes", EmitDefaultValue=false)]
        public List<CompanyType> CompanyTypes { get; set; }
        /// <summary>
        /// The unique identifier of this entity
        /// </summary>
        /// <value>The unique identifier of this entity</value>
        [DataMember(Name="Id", EmitDefaultValue=false)]
        public int? Id { get; set; }
        /// <summary>
        /// The id of the user who created this entity
        /// </summary>
        /// <value>The id of the user who created this entity</value>
        [DataMember(Name="CreatedBy", EmitDefaultValue=false)]
        public int? CreatedBy { get; set; }
        /// <summary>
        /// The id of the last user who modified this entity
        /// </summary>
        /// <value>The id of the last user who modified this entity</value>
        [DataMember(Name="UpdatedBy", EmitDefaultValue=false)]
        public int? UpdatedBy { get; set; }
        /// <summary>
        /// The date and time this entity was created, in UTC
        /// </summary>
        /// <value>The date and time this entity was created, in UTC</value>
        [DataMember(Name="CreatedOn", EmitDefaultValue=false)]
        public DateTime? CreatedOn { get; set; }
        /// <summary>
        /// The last date and time this entity was updated, in UTC
        /// </summary>
        /// <value>The last date and time this entity was updated, in UTC</value>
        [DataMember(Name="UpdatedOn", EmitDefaultValue=false)]
        public DateTime? UpdatedOn { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Company {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  IndustrialSector: ").Append(IndustrialSector).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  DebitorNumber: ").Append(DebitorNumber).Append("\n");
            sb.Append("  CreditorNumber: ").Append(CreditorNumber).Append("\n");
            sb.Append("  DefaultAddress: ").Append(DefaultAddress).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("  CompanyTypes: ").Append(CompanyTypes).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  CreatedBy: ").Append(CreatedBy).Append("\n");
            sb.Append("  UpdatedBy: ").Append(UpdatedBy).Append("\n");
            sb.Append("  CreatedOn: ").Append(CreatedOn).Append("\n");
            sb.Append("  UpdatedOn: ").Append(UpdatedOn).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Company);
        }

        /// <summary>
        /// Returns true if Company instances are equal
        /// </summary>
        /// <param name="other">Instance of Company to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Company other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Name == other.Name ||
                    this.Name != null &&
                    this.Name.Equals(other.Name)
                ) && 
                (
                    this.IndustrialSector == other.IndustrialSector ||
                    this.IndustrialSector != null &&
                    this.IndustrialSector.Equals(other.IndustrialSector)
                ) && 
                (
                    this.Description == other.Description ||
                    this.Description != null &&
                    this.Description.Equals(other.Description)
                ) && 
                (
                    this.DebitorNumber == other.DebitorNumber ||
                    this.DebitorNumber != null &&
                    this.DebitorNumber.Equals(other.DebitorNumber)
                ) && 
                (
                    this.CreditorNumber == other.CreditorNumber ||
                    this.CreditorNumber != null &&
                    this.CreditorNumber.Equals(other.CreditorNumber)
                ) && 
                (
                    this.DefaultAddress == other.DefaultAddress ||
                    this.DefaultAddress != null &&
                    this.DefaultAddress.Equals(other.DefaultAddress)
                ) && 
                (
                    this.CustomFields == other.CustomFields ||
                    this.CustomFields != null &&
                    this.CustomFields.SequenceEqual(other.CustomFields)
                ) && 
                (
                    this.CompanyTypes == other.CompanyTypes ||
                    this.CompanyTypes != null &&
                    this.CompanyTypes.SequenceEqual(other.CompanyTypes)
                ) && 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.CreatedBy == other.CreatedBy ||
                    this.CreatedBy != null &&
                    this.CreatedBy.Equals(other.CreatedBy)
                ) && 
                (
                    this.UpdatedBy == other.UpdatedBy ||
                    this.UpdatedBy != null &&
                    this.UpdatedBy.Equals(other.UpdatedBy)
                ) && 
                (
                    this.CreatedOn == other.CreatedOn ||
                    this.CreatedOn != null &&
                    this.CreatedOn.Equals(other.CreatedOn)
                ) && 
                (
                    this.UpdatedOn == other.UpdatedOn ||
                    this.UpdatedOn != null &&
                    this.UpdatedOn.Equals(other.UpdatedOn)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Name != null)
                    hash = hash * 59 + this.Name.GetHashCode();
                if (this.IndustrialSector != null)
                    hash = hash * 59 + this.IndustrialSector.GetHashCode();
                if (this.Description != null)
                    hash = hash * 59 + this.Description.GetHashCode();
                if (this.DebitorNumber != null)
                    hash = hash * 59 + this.DebitorNumber.GetHashCode();
                if (this.CreditorNumber != null)
                    hash = hash * 59 + this.CreditorNumber.GetHashCode();
                if (this.DefaultAddress != null)
                    hash = hash * 59 + this.DefaultAddress.GetHashCode();
                if (this.CustomFields != null)
                    hash = hash * 59 + this.CustomFields.GetHashCode();
                if (this.CompanyTypes != null)
                    hash = hash * 59 + this.CompanyTypes.GetHashCode();
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.CreatedBy != null)
                    hash = hash * 59 + this.CreatedBy.GetHashCode();
                if (this.UpdatedBy != null)
                    hash = hash * 59 + this.UpdatedBy.GetHashCode();
                if (this.CreatedOn != null)
                    hash = hash * 59 + this.CreatedOn.GetHashCode();
                if (this.UpdatedOn != null)
                    hash = hash * 59 + this.UpdatedOn.GetHashCode();
                return hash;
            }
        }
    }

}
