/* 
 * HQ API Entities
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HQSB.API.SDK.Api;
using HQSB.API.SDK.Model;
using HQSB.API.SDK.Client;
using System.Reflection;

namespace HQSB.API.SDK.Test
{
    /// <summary>
    ///  Class for testing Article
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ArticleTests
    {
        // TODO uncomment below to declare an instance variable for Article
        //private Article instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Article
            //instance = new Article();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Article
        /// </summary>
        [Test]
        public void ArticleInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Article
            //Assert.IsInstanceOfType<Article> (instance, "variable 'instance' is a Article");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'ArticleCategoryId'
        /// </summary>
        [Test]
        public void ArticleCategoryIdTest()
        {
            // TODO unit test for the property 'ArticleCategoryId'
        }
        /// <summary>
        /// Test the property 'BaseType'
        /// </summary>
        [Test]
        public void BaseTypeTest()
        {
            // TODO unit test for the property 'BaseType'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Test]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'ArticleSalesPriceId'
        /// </summary>
        [Test]
        public void ArticleSalesPriceIdTest()
        {
            // TODO unit test for the property 'ArticleSalesPriceId'
        }
        /// <summary>
        /// Test the property 'ArticleSalesPrice'
        /// </summary>
        [Test]
        public void ArticleSalesPriceTest()
        {
            // TODO unit test for the property 'ArticleSalesPrice'
        }
        /// <summary>
        /// Test the property 'ArticleCategory'
        /// </summary>
        [Test]
        public void ArticleCategoryTest()
        {
            // TODO unit test for the property 'ArticleCategory'
        }
        /// <summary>
        /// Test the property 'ArticleSupplierQuotations'
        /// </summary>
        [Test]
        public void ArticleSupplierQuotationsTest()
        {
            // TODO unit test for the property 'ArticleSupplierQuotations'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Test]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Test]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Test]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }

    }

}
