/* 
 * HQ API Entities
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HQSB.API.SDK.Api;
using HQSB.API.SDK.Model;
using HQSB.API.SDK.Client;
using System.Reflection;

namespace HQSB.API.SDK.Test
{
    /// <summary>
    ///  Class for testing CustomFieldDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CustomFieldDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for CustomFieldDefinition
        //private CustomFieldDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CustomFieldDefinition
            //instance = new CustomFieldDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CustomFieldDefinition
        /// </summary>
        [Test]
        public void CustomFieldDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CustomFieldDefinition
            //Assert.IsInstanceOfType<CustomFieldDefinition> (instance, "variable 'instance' is a CustomFieldDefinition");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Test]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'RightLevelRead'
        /// </summary>
        [Test]
        public void RightLevelReadTest()
        {
            // TODO unit test for the property 'RightLevelRead'
        }
        /// <summary>
        /// Test the property 'RightLevelWrite'
        /// </summary>
        [Test]
        public void RightLevelWriteTest()
        {
            // TODO unit test for the property 'RightLevelWrite'
        }
        /// <summary>
        /// Test the property 'IsRequired'
        /// </summary>
        [Test]
        public void IsRequiredTest()
        {
            // TODO unit test for the property 'IsRequired'
        }
        /// <summary>
        /// Test the property 'TypeText'
        /// </summary>
        [Test]
        public void TypeTextTest()
        {
            // TODO unit test for the property 'TypeText'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Options'
        /// </summary>
        [Test]
        public void OptionsTest()
        {
            // TODO unit test for the property 'Options'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Test]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Test]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Test]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }

    }

}
