/* 
 * HQ API Entities
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using HQSB.API.SDK.Api;
using HQSB.API.SDK.Model;
using HQSB.API.SDK.Client;
using System.Reflection;

namespace HQSB.API.SDK.Test
{
    /// <summary>
    ///  Class for testing Project
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProjectTests
    {
        // TODO uncomment below to declare an instance variable for Project
        //private Project instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Project
            //instance = new Project();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Project
        /// </summary>
        [Test]
        public void ProjectInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Project
            //Assert.IsInstanceOfType<Project> (instance, "variable 'instance' is a Project");
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PlannedStartDate'
        /// </summary>
        [Test]
        public void PlannedStartDateTest()
        {
            // TODO unit test for the property 'PlannedStartDate'
        }
        /// <summary>
        /// Test the property 'PlannedEndDate'
        /// </summary>
        [Test]
        public void PlannedEndDateTest()
        {
            // TODO unit test for the property 'PlannedEndDate'
        }
        /// <summary>
        /// Test the property 'Subsystems'
        /// </summary>
        [Test]
        public void SubsystemsTest()
        {
            // TODO unit test for the property 'Subsystems'
        }
        /// <summary>
        /// Test the property 'ProjectTemplateId'
        /// </summary>
        [Test]
        public void ProjectTemplateIdTest()
        {
            // TODO unit test for the property 'ProjectTemplateId'
        }
        /// <summary>
        /// Test the property 'ProjectTemplate'
        /// </summary>
        [Test]
        public void ProjectTemplateTest()
        {
            // TODO unit test for the property 'ProjectTemplate'
        }
        /// <summary>
        /// Test the property 'ProjectStatusId'
        /// </summary>
        [Test]
        public void ProjectStatusIdTest()
        {
            // TODO unit test for the property 'ProjectStatusId'
        }
        /// <summary>
        /// Test the property 'ProjectStatus'
        /// </summary>
        [Test]
        public void ProjectStatusTest()
        {
            // TODO unit test for the property 'ProjectStatus'
        }
        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Test]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }
        /// <summary>
        /// Test the property 'Company'
        /// </summary>
        [Test]
        public void CompanyTest()
        {
            // TODO unit test for the property 'Company'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Test]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CreatedBy'
        /// </summary>
        [Test]
        public void CreatedByTest()
        {
            // TODO unit test for the property 'CreatedBy'
        }
        /// <summary>
        /// Test the property 'UpdatedBy'
        /// </summary>
        [Test]
        public void UpdatedByTest()
        {
            // TODO unit test for the property 'UpdatedBy'
        }
        /// <summary>
        /// Test the property 'CreatedOn'
        /// </summary>
        [Test]
        public void CreatedOnTest()
        {
            // TODO unit test for the property 'CreatedOn'
        }
        /// <summary>
        /// Test the property 'UpdatedOn'
        /// </summary>
        [Test]
        public void UpdatedOnTest()
        {
            // TODO unit test for the property 'UpdatedOn'
        }

    }

}
